apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: myspace
  labels:
    name: db-deploy
spec:
  replicas: 1
  selector: 
    matchLabels: 
      name: mydb-pod
  template: # the pod that Im going to deploy
    metadata:
      name: mydb-pod
      labels: 
        name: mydb-pod # matchLabel
    spec:
      containers:
        - name: mydb-container
          image: stackupiss/northwind-db:v1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3306

--- 
# starting new file

apiVersion: v1
kind: Service

metadata:
  name: mydb-svc
  namespace: myspace
  labels:
    name: mydb-svc

spec: 
  type: NodePort
  selector: 
    name: mydb-pod # can add in version: 1 etc
  ports: 
  - port: 3306 # service port, recall port binding
    targetPort: 3306 #container port